### ISSUE TITLE
请问如何推流

### ISSUE THREAD

**Issue by Schips-Wong** [sonichy/HTYDLNA#1]
我使用Macst（v0.7, Windows）平台，填入了http://cctvalih5ca.v.myalicdn.com/live/cctv1_2/index.m3u8，进行Play，但是提示‘Load failed’

**Comment by sonichy** [comment]
浏览器（HLS扩展）播放404，这个地址播放不了。

**Comment by Schips-Wong** [comment]
好的，这个地址只是我随便找的（但是源码内默认的地址我Play也不了）。我想尝试播放本地文件，请问介意提供思路或者指导吗，万分感谢。

**Comment by sonichy** [comment]
列表行右键菜单Play
